name: wcs.kiev
favicon: null
layout_spectrum: 0.25148
typography_spectrum: 0.25728
title: Танцы West Coast Swing в Киеве
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-18228139-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dec1dc'
    - '#210423'
    - '#5f325f'
    - '#975b96'
    - '#b18cb2'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
