name: wcs.kiev
favicon: null
layout_spectrum: 0.3986899214796722
typography_spectrum: 0.2286702108103782
title: Танцы West Coast Swing в Киеве
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5654276562854648
  lightness: 0.8816199721768498
  saturation: 0.7633761770557612
  rhythmicContrast: 0.24550452665425837
purpose: []
